import Sidebar from "@/components/common/sidebar";
import type { Metadata } from "next";
import "../../../globals.scss";
import styles from './styles.module.scss'
import ProfileHeader from "@/components/common/profileheader";
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       
    <div>
        <ProfileHeader/>
        <div  className={styles["announcement"]}>SINAQ MÜDDƏTİNİN BİTMƏSİNƏ 5 GÜN QALIB</div>
        <div className={styles["layout-container"]}>
          <Sidebar />
          {children} 
        </div>
   </div>     


  );
}
